### ISSUE TITLE
Modify previously created feature model

### ISSUE THREAD

**Issue by sigurdo** [evelance/feature_model_drawer#1]
A way to save the current feature model so it can be uploaded and modified later would be nice. But it is by no means necessary, since the editor is impressively quick and easy to use (so that you can quickly create the feature model again from scratch) and it is not the right tool for making really large and complex feature models.

**Comment by evelance** [comment]
Thanks for the kind words! The tool is indeed very basic, it was faster to write than to install all the Eclipse modules.

Since SVG is very well integrated into the browser, I cobbled together a new option to import already created SVG diagrams. Does this work for you?

**Comment by sigurdo** [comment]
Wow, that is really cool! It sadly did not fully work out to upload the SVG I saved last week for further editing, since it seems like you did some changes to how the SVG is actually rendered, but I tested out making a small model now and it worked nicely.

**Comment by evelance** [comment]
Could you attach the problematic SVG, or send it to me privately?

**Comment by sigurdo** [comment]
Sorry for not answering, you must have answered so quickly that I didn't even get the notification. ~~Here it is.~~

**EDIT:** Don't use this one, GitHub clearly modified it during upload.

![feature_model](https://github.com/evelance/feature_model_drawer/assets/36281346/93a5f961-2b7b-4c18-a6d0-312cc14cadaa)

**Comment by sigurdo** [comment]
Huh, looks like GitHub modified it when I pasted it directly in the chat, it does not appear exactly like before, use [this one](https://sigurdt.no/feature_model.svg) instead.

**Comment by evelance** [comment]
Thanks for the diagram!

The import failed because your diagram is slightly buggy (see the empty box in the top left corner?). This bug is already fixed for new diagrams but the import of old diagrams containing this buggy box did not work.

I fixed the import and you should now be able to import your old diagrams, too.
